name: cyr_flutter_core
description: Shared Flutter core — network, bloc, dependency injection, and presentation helpers.
version: 0.1.0
homepage:

environment:
  sdk: ^3.5.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.7.0
  retrofit: 4.9.2
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  meta: ^1.15.0
  anti_hook_vpn: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  retrofit_generator: 10.2.6

flutter:
